language: go
go:
  - tip
  - 1.3
script: 
  - go get code.google.com/p/go.tools/cmd/vet
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/kisom/testio/... 
  - go test -cover github.com/kisom/testio/... 
  - go vet github.com/kisom/testio/... 
notifications:
  email:
    recipients:
      - coder@kyleisom.net
    on_success: change
    on_failure: change
