sudo: false
language: go
go:
  - tip
  - 1.5
script: 
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/kisom/testio/... 
  - go test -cover github.com/kisom/testio/... 
  - go vet github.com/kisom/testio/... 
notifications:
  email:
    recipients:
      - coder@kyleisom.net
    on_success: change
    on_failure: change
